name: deploy

on:
  # Trigger the workflow on push to main branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  build-and-deploy-book:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2

    # Install dependencies
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install -r requirements-dev.txt

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build machine-learning-das

    # Deploy the book's HTML to gh-pages branch
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: machine-learning-das/_build/html
